# General configuration for experiment
project: "TGLF-MOE"
base_seed: 42
epochs: 20 # 20 
batch: 25 #256
steps_per_epoch: 20 # 200
loss_freq: 10
plot_freq: 100
save_freq: 500
time_warm: 1
time_freq: 500
plot: true
board: false
dataset_workers: 4
dump_dir: "dump"
plot_dir: "plots"

# Model configuration
model:
  latent_dim: 256
  hidden_layer: 4
  input_dim: 31
  target_dim: 4
  num_resnet: 10

  # Gating mechanism configs
  num_experts: 5
  gate_hidden_dim: 128
  gate_hidden_layers: 4
  recover_pred_unit: false # determines if predictions are denormalized

# Optimizer configuration
opt:
  peak_lr: 0.0005
  accumulation_steps: 10
  weight_decay: 0.0001
  warmup_steps: 100 
  decay_steps: 200 
  gnorm_clip: 1.0


# parameters for data loading and data sampling
dataset:
  dataset_root: "qlnn_classification/qlnn_classification"

# hydra cnofigurations (default: no output logging)
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false